# Generated by Django 3.2.18 on 2023-05-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='booked',
            field=models.CharField(choices=[(0, 'Available'), (1, 'Booked')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default=0, max_length=200),
        ),
    ]
