# Generated by Django 3.2.18 on 2023-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0002_auto_20230514_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='booked',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=0, max_length=200),
        ),
    ]
