# Generated by Django 3.2.18 on 2023-05-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0003_auto_20230521_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='booked',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='available', max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='draft', max_length=200),
        ),
    ]
