# Generated by Django 3.2.18 on 2023-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0004_auto_20230521_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[(1, 'Draft'), (2, 'Published')], default=1, max_length=200),
        ),
    ]
