# Generated by Django 3.2.18 on 2023-05-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0005_alter_dog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='booked',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default=0, max_length=200),
        ),
    ]
