# Generated by Django 3.2.18 on 2023-05-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0006_auto_20230521_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default='Draft', max_length=200),
        ),
    ]
