# Generated by Django 3.2.18 on 2023-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0008_alter_dog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
