# Generated by Django 3.2.18 on 2023-05-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homing', '0009_alter_dog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
