# Generated by Django 3.2.18 on 2023-06-10 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20230610_0711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rating',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
