# Generated by Django 3.2.18 on 2023-06-10 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20230610_0728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
